import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../styles/index.css';
import { ToastContainer } from 'react-toastify';
import { QueryClientProvider } from '@tanstack/react-query';
import { QueryClient } from '@/lib/tanstack';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<QueryClientProvider client={QueryClient}>
					<ToastContainer />
					{children}
				</QueryClientProvider>
			</body>
		</html>
	);
}
